#!perl
sub {
    my $logged_in_user = shift;
    return {
        prepare => {
            old_password => {
                required  => 1,
                validator => sub {
                    if ( $logged_in_user->check_password( $_[0] ) ) {
                        return 1;
                    }
                    else {
                        return ( undef, "Password incorrect" );
                    }
                },
            },
            password => {
                required  => 1,
                validator => {
                    class   => 'PasswordPolicy',
                    options => {
                        username      => $logged_in_user->username,
                        minlength     => 8,
                        maxlength     => 70,
                        patternlength => 4,
                        mindiffchars  => 5,
                        disabled      => {
                            digits   => 1,
                            mixed    => 1,
                            specials => 1,
                        }
                    }
                }
            },
            confirm_password => { required => 1 },
            passwords        => {
                validator => 'Group',
                fields    => [ "password", "confirm_password" ],
            },
        }
    };
};
